name: Hello_World

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"

  list_files_job:
    runs-on: ubuntu-20.04
    steps:
      - name: List files
        run: |
          ls

  print_date_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Print Date
        run: |
          date
